use_default_settings: true

general:
  debug: false
  instance_name: "Vantage Search"

search:
  safe_search: 0
  autocomplete: ""
  default_lang: "auto"
  formats:
    - html
    - json

server:
  secret_key: "overridden-by-SEARXNG_SECRET"
  limiter: false
  image_proxy: false

ui:
  static_use_hash: true

outgoing:
  request_timeout: 6.0
  max_request_timeout: 12.0
  pool_connections: 100
  pool_maxsize: 20
  proxies:
    all://:
      - http://172.17.0.1:17890

engines:
  - name: yahoo
    engine: yahoo
    disabled: false
    weight: 1.15

  - name: yandex
    engine: yandex
    disabled: false
    weight: 1.0

  - name: bing
    engine: bing
    disabled: true

  - name: duckduckgo
    engine: duckduckgo
    disabled: true

  - name: google
    engine: google
    disabled: true
